{{- if .Values.vault_settings.gcp_secret_manager }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-db-host/versions/latest" 
        fileName: "db-host"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-prototype-db-user/versions/latest" 
        fileName: "prototype-db-user"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-prototype-db-password/versions/latest" 
        fileName: "prototype-db-password"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-prototype-db/versions/latest" 
        fileName: "prototype-db"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/message-broker-driver/versions/latest" 
        fileName: "message-broker-driver"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-message-broker-connection-string/versions/latest" 
        fileName: "message-broker-connection-string"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-app-secret-key/versions/latest" 
        fileName: "app-secret-key"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/keycloak-certs-endpoint/versions/latest" 
        fileName: "keycloak-certs-endpoint"
  secretObjects:
    - secretName: {{ .Values.secrets.deps_enrichment.secretName }}
      type: Opaque
      data:
      - objectName: "keycloak-certs-endpoint"
        key: keycloak-certs-endpoint
      - objectName: "app-secret-key"
        key: app-secret-key
      - objectName: "message-broker-connection-string"
        key: message-broker-connection-string
      - objectName: "message-broker-driver"
        key: message-broker-driver
      - objectName: "db-host"
        key: db-host
      - objectName: "prototype-db-user"
        key: prototype-db-user
      - objectName: "prototype-db-password"
        key: prototype-db-password
      - objectName: "prototype-db"
        key: prototype-db
{{- end }}
