{{- if .Values.vault_settings.azure_key_vault }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
spec:
  provider: azure
  secretObjects:
  - data:
    - key: app-secret-key
      objectName: app-secret-key
    - key: keycloak-certs-endpoint
      objectName: keycloak-certs-endpoint
    - key: message-broker-driver
      objectName: message-broker-driver
    - key: message-broker-connection-string
      objectName: message-broker-connection-string
    - key: db-host
      objectName: db-host
    - key: prototype-db
      objectName: prototype-db
    - key: prototype-db-user
      objectName: prototype-db-user
    - key: prototype-db-password
      objectName: prototype-db-password
    secretName: {{ .Values.secrets.deps_prototype.secretName }}
    type: Opaque
  parameters:
    keyvaultName: {{ .Values.azure_kv_settings.keyvaultName }}
    tenantId: {{ .Values.azure_kv_settings.tenantId }}
    vaultKubernetesMountPath: {{ .Values.csi.vaultKubernetesMountPath }}
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.azure_kv_settings.userAssignedIdentityID }}
    resourceGroup:  {{ .Values.azure_kv_settings.resourceGroup }}
    subscriptionId: {{ .Values.azure_kv_settings.subscriptionId }}
    objects: |
      array:
        - |
          objectName: "app-secret-key"
          objectType: secret

        - |
          objectName: "keycloak-certs-endpoint"
          objectType: secret

        - |
          objectName: "message-broker-driver"
          objectType: secret

        - |
          objectName: "message-broker-connection-string"
          objectType: secret

        - |
          objectName: "db-host"
          objectType: secret

        - |
          objectName: "prototype-db"
          objectType: secret

        - |
          objectName: "prototype-db-user"
          objectType: secret

        - |
          objectName: "prototype-db-password"
          objectType: secret
{{- end }}
