secrets:
  deps_prototype:
    secretName: deps-prototype
  app_secret_key:
    secretName: app-secret-key
  prototype_database:
    secretName: prototype-database
  keycloak_certs_endpoint:
    secretName: keycloak-certs-endpoint
  common_secret:
    secretName: common-secret
  rabbitmq_password:
    secretName: rabbitmq-password
  security_certs:
    secretName: security-certs
  redis_password:
    secretName: redis-password
  kafka_secrets:
    secretName: kafka-secrets
  database_ssl_secret:
    secretName: database-ssl-secret
  telemetry_secrets:
    secretName: telemetry-secrets

helm_logs_job:
  serviceAccountName: gitlab-ci
  image:
    path: "/base/kubernetes-helm"
    pullPolicy: IfNotPresent
    tag: "0.1.1"
  resources: {}

registry: ""
env: ""

prototype:
  replicaCount: 1
  image:
    path: "/deps-dev-x01/deps-prototype"
    pullPolicy: IfNotPresent
    tag: ""
  imagePullSecrets: artifactory
  service:
    type: ClusterIP
    port: 8000
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

prototype_consumer:
  replicaCount: 1
  image:
    path: '/deps-dev-x01/deps-prototype'
    pullPolicy: IfNotPresent
    tag: ''
  imagePullSecrets: artifactory
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

certs_location:
  certs_default_path: "/tmp/ssl"
  database_sslcerts_path: "/home/dbcerts"

prototype_settings:
  ENV: dev

  DATABASE_PORT: '5432'
  DATABASE_DRIVER: psycopg2
  DATABASE_DIALECT: postgresql
  DATABASE_REQUIRE_SECURE_TRANSPORT: false
  DATABASE_SSLKEY_PATH: "/home/dbcerts/tls.key"
  DATABASE_SSLCERT_PATH: "/home/dbcerts/tls.crt"
  DATABASE_SSLROOTCERT_PATH: "/home/dbcerts/root.crt"

  AUTH_VERIFY_SSL: false

  LOG_LEVEL: "INFO"
  DOCUMENTATION_ENABLED: "true"

  RABBITMQ_TLS_ENABLED: false

  KAFKA_GROUP_ID: prototype
  KAFKA_AUTO_OFFSET_RESET: earliest
  KAFKA_SECURITY_ENABLED: false

  DOCUMENT_TYPE_URL: 'http://document-type:8000'
  PARSING_URL: 'http://parsing:8000'
  EXTRACTION_URL: 'http://extraction:8000'
  UNIFIER_URL: 'http://unifier:8000'
  FILE_STORAGE_URL: 'http://file-storage-nginx:8000'
  DOCUMENT_URL: 'http://backend:8000'

  # Azure Service Bus
  ASB_SUBSCRIPTION_STRATEGY: 'no_preparation'
  ASB_TOPIC_NAME: 'deps-topic'
  message_broker_asb_without_manage_permission: false

  # Telemetry
  INSTRUMENTATION_ENABLED: false
  SERVICE_NAME: deps-prototype
  EXPORTER_TYPE: azure

helm:
  helm_logs_job_enabled: false

csi:
  csi_default_name: deps-prototype
  vault_namespace: 'k8s-dev'
  roleName: 'k8s-dev'
  vaultKubernetesMountPath: 'kubernetes-dev'

secrets_location:
  secrets_default_path: "/mnt/secrets-store"

service_account:
  serviceAccountName: 'deps-develop'

azure_kv_settings:
  keyvaultName: ""
  tenantId: ""
  userAssignedIdentityID: ""
  resourceGroup: ""
  subscriptionId: ""

vault_settings:
  enabled: false
  hashicorp_vault: false
  azure_key_vault: false
  gcp_secret_manager: false
  aws_secret_manager: false
  aws_secret_manager_region: ''

prototype_vault_enabled:
  env:
  - name: AUTH_CERTS_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: deps-prototype
        key: keycloak-certs-endpoint
  - name: MESSAGING_DRIVER
    valueFrom:
      secretKeyRef:
        name: deps-prototype
        key: message-broker-driver
  - name: MESSAGE_BROKER_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: deps-prototype
        key: message-broker-connection-string
  - name: DATABASE_HOST
    valueFrom:
      secretKeyRef:
        name: deps-prototype
        key: db-host
  - name: DATABASE_DB
    valueFrom:
      secretKeyRef:
        name: deps-prototype
        key: prototype-db
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: deps-prototype
        key: prototype-db-user
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: deps-prototype
        key: prototype-db-password

prototype_vault_disabled:
  env:
  - name: AUTH_CERTS_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: keycloak-certs-endpoint
        key: keycloak-certs-endpoint
  - name: MESSAGING_DRIVER
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: message-broker-driver
  - name: MESSAGE_BROKER_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: message-broker-connection-string
  - name: DATABASE_HOST
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: database-host
  - name: DATABASE_DB
    valueFrom:
      secretKeyRef:
        name: prototype-database
        key: database-db
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: prototype-database
        key: user
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: prototype-database
        key: password

prototype_consumer_vault_enabled:
  env:
  - name: SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: deps-prototype
        key: app-secret-key
  - name: AUTH_CERTS_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: deps-prototype
        key: keycloak-certs-endpoint
  - name: MESSAGING_DRIVER
    valueFrom:
      secretKeyRef:
        name: deps-prototype
        key: message-broker-driver
  - name: MESSAGE_BROKER_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: deps-prototype
        key: message-broker-connection-string
  - name: DATABASE_HOST
    valueFrom:
      secretKeyRef:
        name: deps-prototype
        key: db-host
  - name: DATABASE_DB
    valueFrom:
      secretKeyRef:
        name: deps-prototype
        key: prototype-db
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: deps-prototype
        key: prototype-db-user
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: deps-prototype
        key: prototype-db-password

prototype_consumer_vault_disabled:
  env:
  - name: SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: app-secret-key
        key: app-secret-key
  - name: AUTH_CERTS_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: keycloak-certs-endpoint
        key: keycloak-certs-endpoint
  - name: MESSAGING_DRIVER
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: message-broker-driver
  - name: MESSAGE_BROKER_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: message-broker-connection-string
  - name: DATABASE_HOST
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: database-host
  - name: DATABASE_DB
    valueFrom:
      secretKeyRef:
        name: prototype-database
        key: database-db
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: prototype-database
        key: user
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: prototype-database
        key: password
