apiVersion: v1
kind: ConfigMap
metadata:
  name: prototype-configmap
  labels:
    {{- include "deps-prototype.labels" . | nindent 4 }}
data:
  ENV: {{ .Values.prototype_settings.ENV }}
  DATABASE_PORT: '{{ .Values.prototype_settings.DATABASE_PORT }}'
  DATABASE_DIALECT: '{{ .Values.prototype_settings.DATABASE_DIALECT }}'
  DATABASE_DRIVER: '{{ .Values.prototype_settings.DATABASE_DRIVER }}'
  DATABASE_REQUIRE_SECURE_TRANSPORT: '{{ .Values.prototype_settings.DATABASE_REQUIRE_SECURE_TRANSPORT }}'

  {{- if .Values.prototype_settings.DATABASE_REQUIRE_SECURE_TRANSPORT }}
  DATABASE_SSLKEY: {{ .Values.migration_settings.DATABASE_SSLKEY_PATH }}
  DATABASE_SSLCERT: {{ .Values.migration_settings.DATABASE_SSLCERT_PATH }}
  DATABASE_SSLROOTCERT: {{ .Values.migration_settings.DATABASE_SSLROOTCERT_PATH }}
  {{- end }}

  AUTH_VERIFY_SSL: '{{ .Values.prototype_settings.AUTH_VERIFY_SSL }}'

  LOG_LEVEL: '{{ .Values.prototype_settings.LOG_LEVEL }}'
  DOCUMENTATION_ENABLED: '{{ .Values.prototype_settings.DOCUMENTATION_ENABLED }}'

  KAFKA_GROUP_ID: '{{ .Values.prototype_settings.KAFKA_GROUP_ID }}'
  KAFKA_AUTO_OFFSET_RESET: '{{ .Values.prototype_settings.KAFKA_AUTO_OFFSET_RESET }}'

  DOCUMENT_TYPE_URL: '{{ .Values.prototype_settings.DOCUMENT_TYPE_URL }}'
  PARSING_URL: '{{ .Values.prototype_settings.PARSING_URL }}'
  EXTRACTION_URL: '{{ .Values.prototype_settings.EXTRACTION_URL }}'
  UNIFIER_URL: '{{ .Values.prototype_settings.UNIFIER_URL }}'
  FILE_STORAGE_URL: '{{ .Values.prototype_settings.FILE_STORAGE_URL }}'
  DOCUMENT_URL: '{{ .Values.prototype_settings.DOCUMENT_URL }}'

  {{ if .Values.prototype_settings.RABBITMQ_TLS_ENABLED }}
  RABBITMQ_TLS_HOST: '{{ .Values.prototype_settings.RABBITMQ_TLS_HOST }}'
  RABBITMQ_TLS_PORT: '{{ .Values.prototype_settings.RABBITMQ_TLS_PORT }}'
  RABBITMQ_TLS_USER: '{{ .Values.prototype_settings.RABBITMQ_TLS_USER }}'
  RABBITMQ_TLS_VHOST: '{{ .Values.prototype_settings.RABBITMQ_TLS_VHOST }}'
  RABBITMQ_TLS_SUBJECT: '{{ .Values.prototype_settings.RABBITMQ_TLS_SUBJECT }}'
  RABBITMQ_TLS_CA_CERT: '{{ .Values.prototype_settings.RABBITMQ_TLS_CA_CERT }}'
  RABBITMQ_TLS_CLIENT_CERT: '{{ .Values.prototype_settings.RABBITMQ_TLS_CLIENT_CERT }}'
  RABBITMQ_TLS_CLIENT_KEY: '{{ .Values.prototype_settings.RABBITMQ_TLS_CLIENT_KEY }}'
  {{ end }}

  {{ if .Values.prototype_settings.KAFKA_SECURITY_ENABLED }}
  KAFKA_SASL_MECHANISM: '{{ .Values.prototype_settings.KAFKA_SASL_MECHANISM }}'
  KAFKA_SECURITY_PROTOCOL: '{{ .Values.prototype_settings.KAFKA_SECURITY_PROTOCOL }}'
  {{ end }}
  {{ if .Values.prototype_settings.message_broker_asb_without_manage_permission }}
  ASB_SUBSCRIPTION_STRATEGY: '{{ .Values.prototype_settings.ASB_SUBSCRIPTION_STRATEGY }}'
  {{ end }}
  ASB_TOPIC_NAME: '{{ .Values.prototype_settings.ASB_TOPIC_NAME }}'

  # Telemetry
  INSTRUMENTATION_ENABLED: '{{ .Values.prototype_settings.INSTRUMENTATION_ENABLED }}'
  SERVICE_NAME: '{{ .Values.prototype_settings.SERVICE_NAME }}'
  EXPORTER_TYPE: '{{ .Values.prototype_settings.EXPORTER_TYPE }}'
