prototype:
  image:
    path: "/deps-presale-x01/deps-prototype"
    pullPolicy: Always
  resources: {}

prototype_settings:
  ENV: presale
  LOG_LEVEL: "INFO"

  DATABASE_REQUIRE_SECURE_TRANSPORT: false

migration_settings:
  DATABASE_REQUIRE_SECURE_TRANSPORT: false

prototype_consumer:
  image:
    path: "/deps-presale-x01/deps-prototype"
    pullPolicy: Always

migrator:
  image:
    path: "/deps-presale-x01/deps-prototype-migrator"
    pullPolicy: Always

helm:
  helm_logs_job_enabled: false

csi:
  vault_namespace: 'k8s-presale'
  roleName: 'k8s-presale'
  vaultKubernetesMountPath: 'kubernetes-presale'

service_account:
  serviceAccountName: 'deps-presale'
