prototype:
  image:
    path: "/deps-platform/deps-prototype"
  resources: {}

prototype_settings:
  ENV: other
  LOG_LEVEL: "INFO"

  DATABASE_REQUIRE_SECURE_TRANSPORT: false

migration_settings:
  DATABASE_REQUIRE_SECURE_TRANSPORT: false

prototype_consumer:
  image:
    path: "/deps-platform/deps-prototype"

migrator:
  image:
    path: "/deps-platform/deps-prototype-migrator"

helm:
  helm_logs_job_enabled: false

csi:
  vault_namespace: 'k8s-other'
  roleName: 'k8s-other'
  vaultKubernetesMountPath: 'kubernetes-other'

service_account:
  serviceAccountName: 'deps-other'
